name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore .\SupportFunctions\SupportFunctions.sln
    - name: Build
      run: dotnet build --no-restore .\SupportFunctions\SupportFunctions.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal .\SupportFunctions\SupportFunctions.sln
